# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kv15L_SACPjzQg6IOg72kBXobU0ZnrVp
"""

import numpy as np
import streamlit as st
import matplotlib.pyplot as plt
from scipy.special import lambertw

def IRR(
    Mvn,        # капитальные вложения, руб
    Tvosst,     # срок восстановления, лет
    Msod,       # эксплуатационные затраты, руб/год
    Cp,         # цена продукции, руб
    Kteh,       # технологический коэффициент
    Ktg,        # коэффициент готовности
    Tpl,        # производительность, ед/год
    Tvosstso,   # срок восстановления СО, лет
    Y           # время, лет
):
    A = (
        Msod * Tvosst
        - Cp * Kteh * Ktg * Tpl * Tvosst
        + Cp * Kteh * Ktg * Tpl * Tvosstso
    )

    W = lambertw((A * Y / (Mvn * Tvosst)) * np.exp((A * Y) / (Mvn * Tvosst)))

    irr = (
        -Msod * Tvosst * Y
        + Cp * Kteh * Ktg * Tpl * Tvosst * Y
        - Cp * Kteh * Ktg * Tpl * Tvosstso * Y
        + Mvn * Tvosst * W.real
    ) / (Mvn * Tvosst * Y)

    return irr


st.set_page_config(page_title="IRR проекта", layout="wide")
st.title("Интерактивный расчёт IRR проекта")

st.sidebar.header("Параметры проекта")

Kteh = st.sidebar.slider("Технологический коэффициент", 20, 200, 100)
Tpl = st.sidebar.slider("Производительность, ед/год", 1000, 10000, 5000, step=10)
Tvosst = st.sidebar.slider("Срок восстановления, лет", 6, 24, 12)
Msod = st.sidebar.slider("Эксплуатационные затраты, руб/год", 600_000, 1_800_000, 1_000_000, step=100_000)
Cp = st.sidebar.slider("Цена продукции, руб", 1_000, 1_000_000, 50_000, step=1_000)
Ktg = st.sidebar.slider("Коэффициент готовности", 0.01, 0.2, 0.1, step=0.01)

Y = np.linspace(0.1, 10, 300)

irr = IRR(
    Mvn=20_000_000,
    Tvosst=Tvosst,
    Msod=Msod,
    Cp=Cp,
    Kteh=Kteh,
    Ktg=Ktg,
    Tpl=Tpl,
    Tvosstso=2,
    Y=Y
)

fig, ax = plt.subplots()
ax.plot(Y, irr * 100)
ax.set_xlabel("Время, лет")
ax.set_ylabel("IRR, %")
ax.grid(True)

st.pyplot(fig)